# Generated by Django 5.0.6 on 2024-11-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiry',
            name='licence_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.owner'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='licence_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.owner'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='violation_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fine',
            name='violation_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='owner',
            name='image',
            field=models.ImageField(upload_to='owner_images/'),
        ),
    ]
